### ISSUE TITLE
Performance with AngularJS

### ISSUE THREAD

**Issue by radarfox** [js-data/js-data-localstorage#15]
Hello Jason,

I think there is a big performance problem in part of this adapter when using with AngularJS.

If you are calling `create` or `destroy` on many items (thousands), you end up with `$rootScope.$apply` for every item, and huge lags!

Why?

1. In this adapter `setTimeout` is called for every injected item here https://github.com/js-data/js-data-localstorage/blob/master/src/index.js#L44
2. In each of timeout execution `inject` for that item is invoked
3. And then js-data-angular call `$apply` as reaction on that https://github.com/js-data/js-data-angular/blob/master/src/index.js#L199

I have replaced `setTimeout` for sync callback as hotfix, but I am not sure if thats good.

**Comment by jmdobry** [comment]
Thanks for bringing this up. There are a couple ways to deal with this at the moment:

- Don't use js-data-angular, but instead use js-data directly, as js-data is not coupled to Angular's $digest loop.
- Use `destroyAll` instead of `destroy` to delete many items at once.
- Keep your using hotfix, though I'm not sure about its implications
- Write a batch create method yourself, until one can be added to js-data-localstorage

I am planning to add a batch create method that can create many items at once.

**Comment by radarfox** [comment]
* Not using `js-data-angular` is kind of extreme solution. I would miss other usefull features as $http integration.
* `destroyAll ` is not helping, as it simply calls `destroy` on each item with no performance optimalizations https://github.com/js-data/js-data-localstorage/blob/master/src/index.js#L386
* What do you mean by "batch create"? Something like implementating new function `createAll` (similar to `deleteAll`)? Wouldnt that required modifications to the core `js-data` module?

**Comment by jmdobry** [comment]
> destroyAll is not helping, as it simply calls destroy on each item with no performance optimalizations

Oh yeah, I forgot. Other adapters that connect to actual databases are able to optimize this method. localStorage doesn't have any collection-based operations.

> What do you mean by "batch create"? Something like implementating new function createAll (similar to deleteAll)?

Something like this: `User.createMany([{ name: 'Bob' }, { name: 'John' }])`

> Wouldnt that required modifications to the core js-data module?

Yes, but only if you want to be able to call `DS#createMany`. Adapters can be used directly when necessary.
