### ISSUE TITLE
Performance with many resource items

### ISSUE THREAD

**Issue by radarfox** [js-data/js-data-localstorage#16]
Hello Jason,

when I was fighting bug #14 I discovered that this adapter has trouble with many created items.

I think its because od `ids` maps you are using.

Conditions:

1. Lets `create` lots of data in localstorage (about tens of thousands)
2. I am lazy, so I let this adapter to generate a new client id content - unfortunately it is using super-long UUID format.
3. As I inject more and more data, the `ids` maps are getting HUGE (about 40 chars per item).
4. On top of all `create` of each item calls `ensureId` https://github.com/js-data/js-data-localstorage/blob/master/src/index.js#L345
5. The `ensureId` then calls `getIds` which deserialize and then again serialze the whole `ids` map. https://github.com/js-data/js-data-localstorage/blob/master/src/index.js#L77
7. I end up with some sort of exponencial complexity slowing down creating of new items. Performance loss is noticable even with few thousand items.

I think the same problem is for `destroy` function.

Do you have any clue of solving this problem? I am not sure what are you use these `ids` maps for.

At least i would welcome switch to shorter id generator, or possibility to change to custom one.

**Comment by jmdobry** [comment]
> At least i would welcome switch to shorter id generator, or possibility to change to custom one.

You can provide the id yourself during create, which requires no changes to js-data-localstorage.

Again, a batch create method would solve these performance issues. Creating thousands of items one by one is not very efficient. If you have ideas on how to improve the current implementation without breaking changes and keeping the current API, I would like to hear them.

**Comment by jmdobry** [comment]
In js-data-localstorage 2.3.0, where before you did something like this:

```js
Promise.all([
  User.create({ name: 'John' }),
  User.create({ name: 'Sally' })
]).then(function (users) { ... })
```

you can now do this:

```js
adapter.createMany(User, [
  { name: 'John' },
  { name: 'Sally' }
]).then(function (users) {
  return User.inject(users);
}).then(function (users) { ... }
```

and when `createMany` is added to js-data, you will be able to do this:

```js
User.createMany([
  { name: 'John' },
  { name: 'Sally' }
]).then(function (users) { ... }
```

**Comment by radarfox** [comment]
Wow, that was fast. Good job.

I was only curious about naming. Why did you implemented `createMany` instead if `createAll`? I thought you wanted to keep API naming aka. `destroy`/`destroyAll` and `find`/`findAll`. On the other hand i find "many" probably more semantic then "all".

If you are planing to implement this new feature in core js-data, I would also recommend adding `updateMany` / `updateAll` for setting the same data on multiple models, so you will have complete set of these performance optimized methods.

Anywas, thanks for a great fix.

**Comment by jmdobry** [comment]
Here is how the naming will work:

- `DS#create(props)` - Create a single item from `props`, resolve with the created item
- `DS#createMany(items)` - Create many items from the `items`array, resolve with the created items
- `DS#update(id, props)` - Apply update from `props` to the item with `id` as id
- `DS#updateAll(query, props)` - Apply update from `props` to all items selected by `query`
- `DS#updateMany(updates)` - Apply individual updates for each item in `updates` (each `update` will have to have the id of the item to be updated)
- `DS#destroy(id)` - Destroy the item with the given id
- `DS#destroyAll(query)` - Destroy all items selected by `query`
- `DS#find(id)` - Find the item with the given id
- `DS#findAll(query)` - Find the items selected by `query`

Hopefully from that you can see how the convention works. Basically, "method" does a single operation for a single item, "methodAll" does a single operation for a collection of items selected by a query, and "methodMany" does multiple operations for multiple items in batch. Hence, why it's named createMany, not createAll. It doesn't make sense to have a `createAll(query, props)` method.

`createMany` and `updateMany` will be batched versions of `create` and `update`, unlike `updateAll` which is performing a single update for a collection of items selected by a query.

**Comment by radarfox** [comment]
Thank you for the quick fix.

I have successfully used this new function for implementation of localstorage fallback when offline. The performance is much better then before.

Looking forward for implementation on DS core.
