### ISSUE TITLE
"Converting circular structure to JSON" when saving a modal with loaded hasMany relations

### ISSUE THREAD

**Issue by bfanger** [js-data/js-data-localstorage#7]
According to https://github.com/js-data/js-data-angular/issues/299 this should be fixed in js-data 1.1.0 but i'm using:
* js-data-angular v2.2.3 
* js-data-localstorage v1.0.1
* js-data v1.5.11

Am I missing an configuration option to activate the "removeCircular" util method?

**Comment by jmdobry** [comment]
No, this is a bug in js-data-localstorage. Thanks for catching it.

**Comment by bfanger** [comment]
Thanks for the quick fix. Works like a charm!
